services:
  text-analyzer:
    build: 
      context: ./text-analyzer
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - GIGACHAT_CLIENT_ID=MDE5YTVmM2UtZWU0Ny03NGQ0LWE1MWQtMWNhNTc4MzY5ODNl
      - GIGACHAT_CLIENT_SECRET=NWQxZWNmMmEtZWIxNi00YmU0LWI5ZWUtODczMDYzMWEzZTE3
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    networks:
      - app-network

  image-analyzer:
    build:
      context: ./image-analyzer
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - app-network

  speech-to-text:
    build:
      context: ./speech-to-text
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge